# Generated by Django 3.2.12 on 2022-03-31 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_unit_price_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
    ]
